author: "sh4869 <nobuk4869@gmail.com>"
description: "A pubspec maintenance tool."
homepage: "https://github.com/sh4869/pbsm"
name: "pbsm"
version: "0.1.4"
dependencies: 
  args: "^0.13.7"
  path: "^1.4.1"
  prompt: "^0.1.7"
  pub_client: "^1.0.8"
  pub_semver: "^1.3.2"
  pubspec: "^0.0.5"
  quiver_optional: "^1.0.0"
dev_dependencies: 
  test: "0.12.18+1"
environment: 
  sdk: ">=1.8.0 <2.0.0"
executables: 
  pbsm: "pbsm"
